spring.application.name=manejo-excepciones-avanzado

# Configuración H2
spring.datasource.url=jdbc:h2:mem:productosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Puerto 8080 (por defecto, puedes omitir esta línea)
server.port=8080

# Configuración Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Seguridad de errores
server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-exception=false